services:
  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_DB: validatorinfo_db
      POSTGRES_USER: validatorinfo_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: >
      sh -c "npx prisma migrate deploy &&
             npx tsx server/tools/init-chains.ts &&
             npx prisma migrate dev"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://validatorinfo_user:password@db:5432/validatorinfo_db?schema=public

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - migrations
    environment:
      DATABASE_URL: postgresql://validatorinfo_user:password@db:5432/validatorinfo_db?schema=public
      SERVER_PORT: "3000"
      PUBLIC_URL: "localhost"

  indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    ports:
      - "3001:3001"
    depends_on:
      - migrations
    environment:
      DATABASE_URL: postgresql://validatorinfo_user:password@db:5432/validatorinfo_db?schema=public
      INDEXER_PORT: "3001"

volumes:
  postgres_data:
