create-deps:
		docker run --name validatorinfo -p "5432:5432" -e POSTGRES_DB=validatorinfo_db -e POSTGRES_USER=validatorinfo_user -e POSTGRES_PASSWORD=password -d "postgres:14-bullseye"
		@sleep 5

destroy-deps:
		docker rm -f validatorinfo

deploy-migrations:
		npx prisma migrate deploy

generate-client:
		npx prisma generate

init-chains:
		npx ts-node server/tools/init-chains.ts

generate-schema:
		npx prisma migrate dev

start-indexer:
		npx tsx server/indexer.ts

start-db:
		make destroy-deps
		make create-deps
		make deploy-migrations
		make init-chains
