-- AlterTable
ALTER TABLE "chains" ADD COLUMN     "avg_tx_interval" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "last_uptime_updated" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "uptime_height" INTEGER NOT NULL DEFAULT 0;
